# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Get the fast C bindings:
#   gem install mysql
#   (on OS X: gem install mysql -- --include=/usr/local/lib)
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

production:
  adapter: mysql
  database: redmine
  host: localhost
  username: redmine
  password: r3dm1n3
  encoding: utf8

development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
  
test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000 
 
